//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;

import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> <PERSONAGGIO>
    * f1 -> Azione()
    * f2 -> Bersaglio()
    */
   public void visit(S n);

   /**
    * f0 -> <ALLEATI>
    *       | <NEMICI>
    *       | <PERSONAGGIO>
    */
   public void visit(Bersaglio n);

   /**
    * f0 -> <ATTACCO>
    *       | Magia()
    *       | Oggetto()
    *       | Invocazione()
    *       | TecnicaSpeciale()
    */
   public void visit(Azione n);

   /**
    * f0 -> "lancia"
    * f1 -> ( <ELEMENTALE> | <NONELEMENTALE> | <DISTATO> | <BIANCA> )
    * f2 -> <SU>
    */
   public void visit(Magia n);

   /**
    * f0 -> "usa"
    * f1 -> <NOMEOGGETTO>
    * f2 -> <SU>
    */
   public void visit(Oggetto n);

   /**
    * f0 -> "invoca"
    * f1 -> <GF>
    * f2 -> <SU>
    */
   public void visit(Invocazione n);

   /**
    * f0 -> "esegue"
    * f1 -> <NOMETECNICA>
    * f2 -> <SU>
    */
   public void visit(TecnicaSpeciale n);

}

