/* Generated By:JavaCC: Do not edit this line. ParserCarbuncleConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserCarbuncleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ATTACCO = 9;
  /** RegularExpression Id. */
  int ELEMENTALE = 10;
  /** RegularExpression Id. */
  int NONELEMENTALE = 11;
  /** RegularExpression Id. */
  int DISTATO = 12;
  /** RegularExpression Id. */
  int BIANCA = 13;
  /** RegularExpression Id. */
  int NOMEOGGETTO = 14;
  /** RegularExpression Id. */
  int GF = 15;
  /** RegularExpression Id. */
  int NOMETECNICA = 16;
  /** RegularExpression Id. */
  int ALLEATI = 17;
  /** RegularExpression Id. */
  int NEMICI = 18;
  /** RegularExpression Id. */
  int SU = 19;
  /** RegularExpression Id. */
  int PERSONAGGIO = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"lancia\"",
    "\"usa\"",
    "\"invoca\"",
    "\"esegue\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"attacca\"",
    "<ELEMENTALE>",
    "<NONELEMENTALE>",
    "<DISTATO>",
    "<BIANCA>",
    "<NOMEOGGETTO>",
    "<GF>",
    "<NOMETECNICA>",
    "\"alleati\"",
    "\"nemici\"",
    "\"su\"",
    "<PERSONAGGIO>",
  };

}
