//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "MARCA"
 * f1 -> NomeComposto()
 * f2 -> "MODELLO"
 * f3 -> NomeComposto()
 */
public class Prodotto implements Node {
   public NodeToken f0;
   public NomeComposto f1;
   public NodeToken f2;
   public NomeComposto f3;

   public Prodotto(NodeToken n0, NomeComposto n1, NodeToken n2, NomeComposto n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Prodotto(NomeComposto n0, NomeComposto n1) {
      f0 = new NodeToken("MARCA");
      f1 = n0;
      f2 = new NodeToken("MODELLO");
      f3 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

