//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> Prodotto()
 * f1 -> "QUANTITA"
 * f2 -> <NUM>
 */
public class Residuo implements Node {
   public Prodotto f0;
   public NodeToken f1;
   public NodeToken f2;

   public Residuo(Prodotto n0, NodeToken n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Residuo(Prodotto n0, NodeToken n1) {
      f0 = n0;
      f1 = new NodeToken("QUANTITA");
      f2 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

