//
// Generated by JTB 1.3.2
//

package syntaxtree;

public class DescrizionePeriodo implements Node {
   public NodeToken f0;
   public Periodo f1;
   public NodeOptional f2;
   public NodeToken f3;
   public NodeList f4;
   public NodeToken f5;
   public NodeToken f6;

   public DescrizionePeriodo(NodeToken n0, Periodo n1, NodeOptional n2, NodeToken n3, NodeList n4, NodeToken n5, NodeToken n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public DescrizionePeriodo(Periodo n0, NodeOptional n1, NodeList n2) {
      f0 = new NodeToken("{");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken("{");
      f4 = n2;
      f5 = new NodeToken("}");
      f6 = new NodeToken("}");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

