//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ","
 * f1 -> "VIA"
 * f2 -> NomeComposto()
 * f3 -> [ NumeroCivico() ]
 * f4 -> ","
 * f5 -> <NUM>
 * f6 -> NomeComposto()
 */
public class Indirizzo implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NomeComposto f2;
   public NodeOptional f3;
   public NodeToken f4;
   public NodeToken f5;
   public NomeComposto f6;

   public Indirizzo(NodeToken n0, NodeToken n1, NomeComposto n2, NodeOptional n3, NodeToken n4, NodeToken n5, NomeComposto n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public Indirizzo(NomeComposto n0, NodeOptional n1, NodeToken n2, NomeComposto n3) {
      f0 = new NodeToken(",");
      f1 = new NodeToken("VIA");
      f2 = n0;
      f3 = n1;
      f4 = new NodeToken(",");
      f5 = n2;
      f6 = n3;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

