//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "MAGAZZINO"
 * f1 -> NomeComposto()
 * f2 -> [ Indirizzo() ]
 */
public class Magazzino implements Node {
   public NodeToken f0;
   public NomeComposto f1;
   public NodeOptional f2;

   public Magazzino(NodeToken n0, NomeComposto n1, NodeOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Magazzino(NomeComposto n0, NodeOptional n1) {
      f0 = new NodeToken("MAGAZZINO");
      f1 = n0;
      f2 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

