/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RimanenzaSingola.java
 *
 * Created on 27-gen-2009, 10.33.17
 */

package CaTraSca.gui;

/**
 *
 * @author Cartell
 */
public class RimanenzaSingola extends javax.swing.JPanel {

    /** Creates new form RimanenzaSingola */
    public RimanenzaSingola() {
        initComponents();
    }

    public RimanenzaSingola(String marca, String modello, int quantita)
    {
        initComponents();
        jLabelMarca.setText(marca);
        jLabelModello.setText(modello);
        if (quantita != 0)
            jLabelQuantita.setText("" + quantita);
        else
            jLabelQuantita.setText("");
    }

    public int getIconHeight() { return jLabel.getIcon().getIconHeight(); }
    public int getIconWidth() { return jLabel.getIcon().getIconWidth(); }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane = new javax.swing.JLayeredPane();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModello = new javax.swing.JLabel();
        jLabelQuantita = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(150, 150));
        setMinimumSize(new java.awt.Dimension(150, 150));
        setPreferredSize(new java.awt.Dimension(150, 150));

        jLayeredPane.setName("jLayeredPane"); // NOI18N

        jLabelMarca.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabelMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMarca.setName("jLabelMarca"); // NOI18N
        jLabelMarca.setBounds(20, 40, 110, 20);
        jLayeredPane.add(jLabelMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelModello.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabelModello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModello.setName("jLabelModello"); // NOI18N
        jLabelModello.setBounds(20, 60, 110, 20);
        jLayeredPane.add(jLabelModello, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelQuantita.setFont(new java.awt.Font("Arial Unicode MS", 1, 24));
        jLabelQuantita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuantita.setName("jLabelQuantita"); // NOI18N
        jLabelQuantita.setBounds(20, 80, 110, 40);
        jLayeredPane.add(jLabelQuantita, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 8));
        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CaTraSca/gui/resources/BackGround.png"))); // NOI18N
        jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel.setName("jLabel"); // NOI18N
        jLabel.setBounds(0, 0, 150, 150);
        jLayeredPane.add(jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModello;
    private javax.swing.JLabel jLabelQuantita;
    private javax.swing.JLayeredPane jLayeredPane;
    // End of variables declaration//GEN-END:variables

}
