package parser;

/* Generated By:JavaCC: Do not edit this line. CaTraScaParserTokenManager.java */
import syntaxtree.*;
import java.util.Vector;

/** Token Manager. */
public class CaTraScaParserTokenManager implements CaTraScaParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x8200L) != 0L)
         {
            jjmatchedKind = 32;
            return 101;
         }
         if ((active0 & 0x22L) != 0L)
         {
            jjmatchedKind = 32;
            return 35;
         }
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 32;
            return 29;
         }
         if ((active0 & 0x30080L) != 0L)
         {
            jjmatchedKind = 32;
            return 63;
         }
         if ((active0 & 0x1000L) != 0L)
            return 72;
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 32;
            return 55;
         }
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 32;
            return 25;
         }
         return -1;
      case 1:
         if ((active0 & 0x28222L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 101;
         }
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 28;
         }
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 58;
         }
         if ((active0 & 0x800L) != 0L)
            return 101;
         if ((active0 & 0x10080L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 62;
         }
         return -1;
      case 2:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 61;
         }
         if ((active0 & 0xac022L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 101;
         }
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 65;
         }
         if ((active0 & 0x200L) != 0L)
            return 101;
         return -1;
      case 3:
         if ((active0 & 0xbc0a2L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 3;
            return 101;
         }
         return -1;
      case 4:
         if ((active0 & 0xac0a2L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 101;
         }
         if ((active0 & 0x10000L) != 0L)
            return 101;
         return -1;
      case 5:
         if ((active0 & 0xac0a2L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 5;
            return 101;
         }
         return -1;
      case 6:
         if ((active0 & 0x20000L) != 0L)
            return 101;
         if ((active0 & 0x8c0a2L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 6;
            return 101;
         }
         return -1;
      case 7:
         if ((active0 & 0x84080L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 7;
            return 101;
         }
         if ((active0 & 0x8022L) != 0L)
            return 101;
         return -1;
      case 8:
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 8;
            return 101;
         }
         if ((active0 & 0x80L) != 0L)
            return 101;
         return -1;
      case 9:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 9;
            return 101;
         }
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 10;
            return 101;
         }
         return -1;
      case 11:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 11;
            return 101;
         }
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 12;
            return 101;
         }
         return -1;
      case 13:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 13;
            return 101;
         }
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 15:
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 16:
         if ((active0 & 0x4000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 21);
      case 41:
         return jjStopAtPos(0, 22);
      case 43:
         return jjStopAtPos(0, 20);
      case 44:
         jjmatchedKind = 8;
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 45:
         return jjStopAtPos(0, 13);
      case 58:
         return jjStopAtPos(0, 18);
      case 59:
         return jjStopAtPos(0, 3);
      case 61:
         return jjStopAtPos(0, 6);
      case 65:
         return jjStartNfaWithStates_0(0, 12, 72);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x22L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x30080L);
      case 81:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 123:
         return jjStopAtPos(0, 2);
      case 125:
         return jjStopAtPos(0, 4);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L);
      case 65:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(1, 11, 101);
         return jjMoveStringLiteralDfa2_0(active0, 0x10080L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x4200L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x20020L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 101);
         return jjMoveStringLiteralDfa3_0(active0, 0x8c000L);
      case 68:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 71:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x420L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(3, 10);
         break;
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x14000L);
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 16, 101);
         break;
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 70:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 90:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x4020L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x2L);
      case 90:
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x80L);
      case 79:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(6, 17, 101);
         break;
      case 82:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 84:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
      case 85:
         return jjMoveStringLiteralDfa7_0(active0, 0x20L);
      case 90:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 15, 101);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      case 69:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(7, 5, 101);
         break;
      case 77:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 78:
         return jjMoveStringLiteralDfa8_0(active0, 0x80L);
      case 97:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(7, 1, 101);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000L);
      case 65:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      case 79:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(8, 7, 101);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000L);
      case 90:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000L);
      case 78:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa12_0(active0, 0x4000L);
      case 79:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa13_0(active0, 0x80000L);
      case 90:
         return jjMoveStringLiteralDfa13_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa14_0(active0, 0x80000L);
      case 73:
         return jjMoveStringLiteralDfa14_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(14, 19);
         break;
      case 65:
         return jjMoveStringLiteralDfa15_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 76:
         return jjMoveStringLiteralDfa16_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
static private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa17_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
static private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(17, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 102;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 72:
               case 101:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 63:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                  }
                  else if (curChar == 39)
                  {
                     if (kind > 32)
                        kind = 32;
                     jjCheckNAdd(101);
                  }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 30)
                        kind = 30;
                     jjCheckNAdd(47);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 30)
                        kind = 30;
                  }
                  break;
               case 55:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 25:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 61:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 28:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 58:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 29:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 62:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 35:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 65:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               case 46:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 30)
                     kind = 30;
                  jjCheckNAdd(47);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 30)
                     kind = 30;
                  jjCheckNAdd(47);
                  break;
               case 48:
                  if (curChar == 48 && kind > 30)
                     kind = 30;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 100:
                  if (curChar != 39)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAdd(101);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 72:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 75;
                  else if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 63:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 66;
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 32)
                        kind = 32;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 83)
                     jjAddStates(0, 1);
                  else if (curChar == 70)
                     jjAddStates(2, 3);
                  else if (curChar == 65)
                     jjAddStates(4, 5);
                  else if (curChar == 77)
                     jjAddStates(6, 7);
                  else if (curChar == 71)
                     jjAddStates(8, 9);
                  else if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 44;
                  else if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 25;
                  else if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 18;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 55:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 58;
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 25:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 61:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 90)
                     jjCheckNAdd(0);
                  break;
               case 28:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 85)
                     jjCheckNAdd(27);
                  break;
               case 58:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 29:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 62:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 65;
                  else if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 35:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 65:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(101);
                  }
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 0:
                  if (curChar == 79 && kind > 27)
                     kind = 27;
                  break;
               case 1:
               case 51:
               case 64:
               case 78:
                  if (curChar == 73)
                     jjCheckNAdd(0);
                  break;
               case 2:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if (curChar == 69 && kind > 27)
                     kind = 27;
                  break;
               case 7:
               case 13:
               case 20:
               case 88:
                  if (curChar == 82)
                     jjCheckNAdd(6);
                  break;
               case 8:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 14:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 21:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 26:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 69 && kind > 28)
                     kind = 28;
                  break;
               case 30:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 79 && kind > 29)
                     kind = 29;
                  break;
               case 32:
               case 95:
                  if (curChar == 67)
                     jjCheckNAdd(31);
                  break;
               case 33:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 36:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 84)
                     jjCheckNAdd(31);
                  break;
               case 38:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 50:
                  if (curChar == 71)
                     jjAddStates(8, 9);
                  break;
               case 52:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 56:
                  if (curChar == 78)
                     jjCheckNAdd(0);
                  break;
               case 57:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 59:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 77)
                     jjAddStates(6, 7);
                  break;
               case 66:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 65)
                     jjAddStates(4, 5);
                  break;
               case 69:
                  if (curChar == 76)
                     jjCheckNAdd(6);
                  break;
               case 70:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 73:
                  if (curChar == 84)
                     jjCheckNAdd(0);
                  break;
               case 74:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 70)
                     jjAddStates(2, 3);
                  break;
               case 79:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 83)
                     jjCheckNAdd(27);
                  break;
               case 85:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 83)
                     jjAddStates(0, 1);
                  break;
               case 89:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 96:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAdd(101);
                  break;
               case 101:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(101);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 102 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   94, 99, 83, 86, 72, 76, 63, 67, 55, 59, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\103\141\124\162\141\123\143\141", "\173", "\73", "\175", 
"\103\117\116\124\111\116\125\105", "\75", "\115\101\107\101\132\132\111\116\117", "\54", "\126\111\101", 
"\54\40\116\56", "\104\101", "\101", "\55", 
"\107\111\101\103\105\116\132\101\40\111\116\111\132\111\101\114\105\72", "\121\125\101\116\124\111\124\101", "\115\101\122\103\101", 
"\115\117\104\105\114\114\117", "\72", "\124\122\101\123\106\117\122\115\101\132\111\117\116\105\72", "\53", 
"\50", "\51", null, null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3f87fffffL, 
};
static final long[] jjtoSkip = {
   0x7800000L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[102];
static private final int[] jjstateSet = new int[204];
static protected char curChar;
/** Constructor. */
public CaTraScaParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public CaTraScaParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 102; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
