package parser;

/* Generated By:JavaCC: Do not edit this line. CaTraScaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CaTraScaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MESE = 27;
  /** RegularExpression Id. */
  int BOOL = 28;
  /** RegularExpression Id. */
  int MOVIMENTO = 29;
  /** RegularExpression Id. */
  int NUM = 30;
  /** RegularExpression Id. */
  int CIFRA = 31;
  /** RegularExpression Id. */
  int CARATTERE = 32;
  /** RegularExpression Id. */
  int NOME = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"CaTraSca\"",
    "\"{\"",
    "\";\"",
    "\"}\"",
    "\"CONTINUE\"",
    "\"=\"",
    "\"MAGAZZINO\"",
    "\",\"",
    "\"VIA\"",
    "\", N.\"",
    "\"DA\"",
    "\"A\"",
    "\"-\"",
    "\"GIACENZA INIZIALE:\"",
    "\"QUANTITA\"",
    "\"MARCA\"",
    "\"MODELLO\"",
    "\":\"",
    "\"TRASFORMAZIONE:\"",
    "\"+\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<MESE>",
    "<BOOL>",
    "<MOVIMENTO>",
    "<NUM>",
    "<CIFRA>",
    "<CARATTERE>",
    "<NOME>",
  };

}
