/* Generated By:JavaCC: Do not edit this line. ParserBaseballConstants.java */
package grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserBaseballConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BASE = 5;
  /** RegularExpression Id. */
  int K = 6;
  /** RegularExpression Id. */
  int OUT_VOLO = 7;
  /** RegularExpression Id. */
  int OUT_RUBATA = 8;
  /** RegularExpression Id. */
  int BASE_SU_BALL = 9;
  /** RegularExpression Id. */
  int INTERFERENZA = 10;
  /** RegularExpression Id. */
  int BASE_RUBATA = 11;
  /** RegularExpression Id. */
  int COLPITO = 12;
  /** RegularExpression Id. */
  int ERRORE = 13;
  /** RegularExpression Id. */
  int TIPO_LANCIO = 14;
  /** RegularExpression Id. */
  int CIFRA_NON_NULLA = 15;
  /** RegularExpression Id. */
  int ZERO = 16;
  /** RegularExpression Id. */
  int NOME = 17;
  /** RegularExpression Id. */
  int PAROLA = 18;
  /** RegularExpression Id. */
  int POSIZIONE_DIFESA = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<BASE>",
    "\"K\"",
    "\"F\"",
    "\"CS\"",
    "\"BB\"",
    "\"INT\"",
    "\"SB\"",
    "\"HP\"",
    "\"E\"",
    "<TIPO_LANCIO>",
    "<CIFRA_NON_NULLA>",
    "\"0\"",
    "<NOME>",
    "<PAROLA>",
    "<POSIZIONE_DIFESA>",
    "\"{\"",
    "\"}\"",
    "\"Squadra Ospite:\"",
    "\",\"",
    "\"Squadra Casa:\"",
    "\";\"",
    "\"Arbitro:\"",
    "\"Line-Up squadra ospite:\"",
    "\"Line-Up squadra casa:\"",
    "\"Attacco squadra ospite:\"",
    "\"Attacco squadra casa:\"",
    "\"(\"",
    "\")\"",
  };

}
