//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "Squadra Ospite:"
 * f1 -> <NOME>
 * f2 -> ","
 * f3 -> "Squadra Casa:"
 * f4 -> <NOME>
 * f5 -> ";"
 */
public class Squadre implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeToken f2;
   public NodeToken f3;
   public NodeToken f4;
   public NodeToken f5;

   public Squadre(NodeToken n0, NodeToken n1, NodeToken n2, NodeToken n3, NodeToken n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public Squadre(NodeToken n0, NodeToken n1) {
      f0 = new NodeToken("Squadra Ospite:");
      f1 = n0;
      f2 = new NodeToken(",");
      f3 = new NodeToken("Squadra Casa:");
      f4 = n1;
      f5 = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

