//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu);
   public void visit(NodeListOptional n, A argu);
   public void visit(NodeOptional n, A argu);
   public void visit(NodeSequence n, A argu);
   public void visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> SezioneA()
    * f1 -> SezioneB()
    * f2 -> "{"
    * f3 -> SezioneC()
    * f4 -> "}"
    */
   public void visit(S n, A argu);

   /**
    * f0 -> Squadre()
    * f1 -> Arbitro()
    */
   public void visit(SezioneA n, A argu);

   /**
    * f0 -> "Squadra Ospite:"
    * f1 -> <NOME>
    * f2 -> ","
    * f3 -> "Squadra Casa:"
    * f4 -> <NOME>
    * f5 -> ";"
    */
   public void visit(Squadre n, A argu);

   /**
    * f0 -> "Arbitro:"
    * f1 -> <NOME>
    * f2 -> ";"
    */
   public void visit(Arbitro n, A argu);

   /**
    * f0 -> ListaLineUp()
    */
   public void visit(SezioneB n, A argu);

   /**
    * f0 -> "Line-Up squadra ospite:"
    * f1 -> LineUp()
    * f2 -> ";"
    * f3 -> "Line-Up squadra casa:"
    * f4 -> LineUp()
    * f5 -> ";"
    */
   public void visit(ListaLineUp n, A argu);

   /**
    * f0 -> Giocatore()
    * f1 -> ","
    * f2 -> Giocatore()
    * f3 -> ","
    * f4 -> Giocatore()
    * f5 -> ","
    * f6 -> Giocatore()
    * f7 -> ","
    * f8 -> Giocatore()
    * f9 -> ","
    * f10 -> Giocatore()
    * f11 -> ","
    * f12 -> Giocatore()
    * f13 -> ","
    * f14 -> Giocatore()
    * f15 -> ","
    * f16 -> Giocatore()
    */
   public void visit(LineUp n, A argu);

   /**
    * f0 -> <NOME>
    * f1 -> <CIFRA_NON_NULLA>
    * f2 -> <POSIZIONE_DIFESA>
    */
   public void visit(Giocatore n, A argu);

   /**
    * f0 -> ( Inning() )+
    */
   public void visit(SezioneC n, A argu);

   /**
    * f0 -> "Attacco squadra ospite:"
    * f1 -> Attacco()
    * f2 -> "Attacco squadra casa:"
    * f3 -> Attacco()
    */
   public void visit(Inning n, A argu);

   /**
    * f0 -> ( "(" Battuta() ")" )+
    */
   public void visit(Attacco n, A argu);

   /**
    * f0 -> ( Lancio() )+
    */
   public void visit(Battuta n, A argu);

   /**
    * f0 -> Giocatore()
    * f1 -> ","
    * f2 -> EffettoBattuta()
    * f3 -> ";"
    */
   public void visit(Lancio n, A argu);

   /**
    * f0 -> PallaBattuta()
    *       | PallaNonBattuta()
    */
   public void visit(EffettoBattuta n, A argu);

   /**
    * f0 -> Esito()
    * f1 -> ( Avanzamento() )*
    */
   public void visit(PallaBattuta n, A argu);

   /**
    * f0 -> <TIPO_LANCIO>
    * f1 -> ( Esito() )?
    * f2 -> ( Avanzamento() )*
    */
   public void visit(PallaNonBattuta n, A argu);

   /**
    * f0 -> ArrivoInBase()
    *       | Eliminazione()
    */
   public void visit(Esito n, A argu);

   /**
    * f0 -> Giocatore()
    * f1 -> Esito()
    */
   public void visit(Avanzamento n, A argu);

   /**
    * f0 -> Base()
    *       | BaseSuBall()
    *       | Interferenza()
    *       | BaseRubata()
    *       | Errore()
    *       | Colpito()
    */
   public void visit(ArrivoInBase n, A argu);

   /**
    * f0 -> StrikeOut()
    *       | OutVolo()
    *       | OutSuBase()
    *       | OutRubata()
    */
   public void visit(Eliminazione n, A argu);

   /**
    * f0 -> <BASE>
    */
   public void visit(Base n, A argu);

   /**
    * f0 -> <BASE_SU_BALL>
    */
   public void visit(BaseSuBall n, A argu);

   /**
    * f0 -> <COLPITO>
    */
   public void visit(Colpito n, A argu);

   /**
    * f0 -> <INTERFERENZA>
    */
   public void visit(Interferenza n, A argu);

   /**
    * f0 -> <BASE_RUBATA>
    * f1 -> <BASE>
    */
   public void visit(BaseRubata n, A argu);

   /**
    * f0 -> <ERRORE>
    * f1 -> <CIFRA_NON_NULLA>
    * f2 -> <BASE>
    */
   public void visit(Errore n, A argu);

   /**
    * f0 -> <K>
    */
   public void visit(StrikeOut n, A argu);

   /**
    * f0 -> <OUT_VOLO>
    * f1 -> <CIFRA_NON_NULLA>
    */
   public void visit(OutVolo n, A argu);

   /**
    * f0 -> <CIFRA_NON_NULLA>
    * f1 -> <CIFRA_NON_NULLA>
    */
   public void visit(OutSuBase n, A argu);

   /**
    * f0 -> <OUT_RUBATA>
    * f1 -> <CIFRA_NON_NULLA>
    */
   public void visit(OutRubata n, A argu);

}

