//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

    @Override
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

    @Override
   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

    @Override
   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

    @Override
   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

    @Override
   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "CaTraSca"
    * f1 -> "{"
    * f2 -> [ Continue() ]
    * f3 -> Magazzino()
    * f4 -> ";"
    * f5 -> ( DescrizionePeriodo() )+
    * f6 -> "}"
    */

    @Override
   public void visit(Scope n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> "CONTINUE"
    * f1 -> "="
    * f2 -> <BOOL>
    */

    @Override
   public void visit(Continue n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "MAGAZZINO"
    * f1 -> NomeComposto()
    * f2 -> [ Indirizzo() ]
    */

    @Override
   public void visit(Magazzino n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> ","
    * f1 -> "VIA"
    * f2 -> NomeComposto()
    * f3 -> [ NumeroCivico() ]
    * f4 -> ","
    * f5 -> <NUM>
    * f6 -> NomeComposto()
    */

    @Override
   public void visit(Indirizzo n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> ", N."
    * f1 -> <NUM>
    */

    @Override
   public void visit(NumeroCivico n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "{"
    * f1 -> Periodo()
    * f2 -> [ Giacenza() ";" ]
    * f3 -> "{"
    * f4 -> ( Azione() )+
    * f5 -> "}"
    * f6 -> "}"
    */

    @Override
   public void visit(DescrizionePeriodo n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> "DA"
    * f1 -> Data()
    * f2 -> "A"
    * f3 -> Data()
    * f4 -> ";"
    */

    @Override
   public void visit(Periodo n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <NUM>
    * f1 -> "-"
    * f2 -> <MESE>
    * f3 -> "-"
    * f4 -> <NUM>
    */

    @Override
   public void visit(Data n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "GIACENZA INIZIALE:"
    * f1 -> Residuo()
    * f2 -> ( "," Residuo() )*
    */

    @Override
   public void visit(Giacenza n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> Prodotto()
    * f1 -> "QUANTITA"
    * f2 -> <NUM>
    */

    @Override
   public void visit(Residuo n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "MARCA"
    * f1 -> NomeComposto()
    * f2 -> "MODELLO"
    * f3 -> NomeComposto()
    */

    @Override
   public void visit(Prodotto n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> ( Movimento() | Trasformazione() )
    * f1 -> ";"
    */

    @Override
   public void visit(Azione n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <MOVIMENTO>
    * f1 -> ":"
    * f2 -> ( Residuo() )+
    */

    @Override
   public void visit(Movimento n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "TRASFORMAZIONE:"
    * f1 -> Materia()
    * f2 -> ( "+" Materia() )*
    * f3 -> "="
    * f4 -> Materia()
    * f5 -> ( "+" Materia() )*
    */

    @Override
   public void visit(Trasformazione n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> <NUM>
    * f2 -> Prodotto()
    * f3 -> ")"
    */

    @Override
   public void visit(Materia n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <NOME>
    * f1 -> ( <NOME> )*
    */

    @Override
   public void visit(NomeComposto n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }
}
