//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "CaTraSca"
    * f1 -> "{"
    * f2 -> [ Continue() ]
    * f3 -> Magazzino()
    * f4 -> ";"
    * f5 -> ( DescrizionePeriodo() )+
    * f6 -> "}"
    */
   public R visit(Scope n, A argu);

   /**
    * f0 -> "CONTINUE"
    * f1 -> "="
    * f2 -> <BOOL>
    */
   public R visit(Continue n, A argu);

   /**
    * f0 -> "MAGAZZINO"
    * f1 -> NomeComposto()
    * f2 -> [ Indirizzo() ]
    */
   public R visit(Magazzino n, A argu);

   /**
    * f0 -> ","
    * f1 -> "VIA"
    * f2 -> NomeComposto()
    * f3 -> [ NumeroCivico() ]
    * f4 -> ","
    * f5 -> <NUM>
    * f6 -> NomeComposto()
    */
   public R visit(Indirizzo n, A argu);

   /**
    * f0 -> ", N."
    * f1 -> <NUM>
    */
   public R visit(NumeroCivico n, A argu);

   /**
    * f0 -> "{"
    * f1 -> Periodo()
    * f2 -> [ Giacenza() ";" ]
    * f3 -> "{"
    * f4 -> ( Azione() )+
    * f5 -> "}"
    * f6 -> "}"
    */
   public R visit(DescrizionePeriodo n, A argu);

   /**
    * f0 -> "DA"
    * f1 -> Data()
    * f2 -> "A"
    * f3 -> Data()
    * f4 -> ";"
    */
   public R visit(Periodo n, A argu);

   /**
    * f0 -> <NUM>
    * f1 -> "-"
    * f2 -> <MESE>
    * f3 -> "-"
    * f4 -> <NUM>
    */
   public R visit(Data n, A argu);

   /**
    * f0 -> "GIACENZA INIZIALE:"
    * f1 -> Residuo()
    * f2 -> ( "," Residuo() )*
    */
   public R visit(Giacenza n, A argu);

   /**
    * f0 -> Prodotto()
    * f1 -> "QUANTITA"
    * f2 -> <NUM>
    */
   public R visit(Residuo n, A argu);

   /**
    * f0 -> "MARCA"
    * f1 -> NomeComposto()
    * f2 -> "MODELLO"
    * f3 -> NomeComposto()
    */
   public R visit(Prodotto n, A argu);

   /**
    * f0 -> ( Movimento() | Trasformazione() )
    * f1 -> ";"
    */
   public R visit(Azione n, A argu);

   /**
    * f0 -> <MOVIMENTO>
    * f1 -> ":"
    * f2 -> ( Residuo() )+
    */
   public R visit(Movimento n, A argu);

   /**
    * f0 -> "TRASFORMAZIONE:"
    * f1 -> Materia()
    * f2 -> ( "+" Materia() )*
    * f3 -> "="
    * f4 -> Materia()
    * f5 -> ( "+" Materia() )*
    */
   public R visit(Trasformazione n, A argu);

   /**
    * f0 -> "("
    * f1 -> <NUM>
    * f2 -> Prodotto()
    * f3 -> ")"
    */
   public R visit(Materia n, A argu);

   /**
    * f0 -> <NOME>
    * f1 -> ( <NOME> )*
    */
   public R visit(NomeComposto n, A argu);

}
