//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJVoidDepthFirst<A> implements GJVoidVisitor<A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
      }
   }

   public void visit(NodeOptional n, A argu) {
      if ( n.present() )
         n.node.accept(this,argu);
   }

   public void visit(NodeSequence n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeToken n, A argu) {}

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "CaTraSca"
    * f1 -> "{"
    * f2 -> [ Continue() ]
    * f3 -> Magazzino()
    * f4 -> ";"
    * f5 -> ( DescrizionePeriodo() )+
    * f6 -> "}"
    */
   public void visit(Scope n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
   }

   /**
    * f0 -> "CONTINUE"
    * f1 -> "="
    * f2 -> <BOOL>
    */
   public void visit(Continue n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
   }

   /**
    * f0 -> "MAGAZZINO"
    * f1 -> NomeComposto()
    * f2 -> [ Indirizzo() ]
    */
   public void visit(Magazzino n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
   }

   /**
    * f0 -> ","
    * f1 -> "VIA"
    * f2 -> NomeComposto()
    * f3 -> [ NumeroCivico() ]
    * f4 -> ","
    * f5 -> <NUM>
    * f6 -> NomeComposto()
    */
   public void visit(Indirizzo n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
   }

   /**
    * f0 -> ", N."
    * f1 -> <NUM>
    */
   public void visit(NumeroCivico n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> "{"
    * f1 -> Periodo()
    * f2 -> [ Giacenza() ";" ]
    * f3 -> "{"
    * f4 -> ( Azione() )+
    * f5 -> "}"
    * f6 -> "}"
    */
   public void visit(DescrizionePeriodo n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
   }

   /**
    * f0 -> "DA"
    * f1 -> Data()
    * f2 -> "A"
    * f3 -> Data()
    * f4 -> ";"
    */
   public void visit(Periodo n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
   }

   /**
    * f0 -> <NUM>
    * f1 -> "-"
    * f2 -> <MESE>
    * f3 -> "-"
    * f4 -> <NUM>
    */
   public void visit(Data n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
   }

   /**
    * f0 -> "GIACENZA INIZIALE:"
    * f1 -> Residuo()
    * f2 -> ( "," Residuo() )*
    */
   public void visit(Giacenza n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
   }

   /**
    * f0 -> Prodotto()
    * f1 -> "QUANTITA"
    * f2 -> <NUM>
    */
   public void visit(Residuo n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
   }

   /**
    * f0 -> "MARCA"
    * f1 -> NomeComposto()
    * f2 -> "MODELLO"
    * f3 -> NomeComposto()
    */
   public void visit(Prodotto n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
   }

   /**
    * f0 -> ( Movimento() | Trasformazione() )
    * f1 -> ";"
    */
   public void visit(Azione n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> <MOVIMENTO>
    * f1 -> ":"
    * f2 -> ( Residuo() )+
    */
   public void visit(Movimento n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
   }

   /**
    * f0 -> "TRASFORMAZIONE:"
    * f1 -> Materia()
    * f2 -> ( "+" Materia() )*
    * f3 -> "="
    * f4 -> Materia()
    * f5 -> ( "+" Materia() )*
    */
   public void visit(Trasformazione n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
   }

   /**
    * f0 -> "("
    * f1 -> <NUM>
    * f2 -> Prodotto()
    * f3 -> ")"
    */
   public void visit(Materia n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
   }

   /**
    * f0 -> <NOME>
    * f1 -> ( <NOME> )*
    */
   public void visit(NomeComposto n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

}
