//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "Attacco squadra ospite:"
 * f1 -> Attacco()
 * f2 -> "Attacco squadra casa:"
 * f3 -> Attacco()
 */
public class Inning implements Node {
   public NodeToken f0;
   public Attacco f1;
   public NodeToken f2;
   public Attacco f3;

   public Inning(NodeToken n0, Attacco n1, NodeToken n2, Attacco n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Inning(Attacco n0, Attacco n1) {
      f0 = new NodeToken("Attacco squadra ospite:");
      f1 = n0;
      f2 = new NodeToken("Attacco squadra casa:");
      f3 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

