//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> Giocatore()
 * f1 -> ","
 * f2 -> EffettoBattuta()
 * f3 -> ";"
 */
public class Lancio implements Node {
   public Giocatore f0;
   public NodeToken f1;
   public EffettoBattuta f2;
   public NodeToken f3;

   public Lancio(Giocatore n0, NodeToken n1, EffettoBattuta n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Lancio(Giocatore n0, EffettoBattuta n1) {
      f0 = n0;
      f1 = new NodeToken(",");
      f2 = n1;
      f3 = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

