//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "Line-Up squadra ospite:"
 * f1 -> LineUp()
 * f2 -> ";"
 * f3 -> "Line-Up squadra casa:"
 * f4 -> LineUp()
 * f5 -> ";"
 */
public class ListaLineUp implements Node {
   public NodeToken f0;
   public LineUp f1;
   public NodeToken f2;
   public NodeToken f3;
   public LineUp f4;
   public NodeToken f5;

   public ListaLineUp(NodeToken n0, LineUp n1, NodeToken n2, NodeToken n3, LineUp n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public ListaLineUp(LineUp n0, LineUp n1) {
      f0 = new NodeToken("Line-Up squadra ospite:");
      f1 = n0;
      f2 = new NodeToken(";");
      f3 = new NodeToken("Line-Up squadra casa:");
      f4 = n1;
      f5 = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

